#!/usr/bin/env python

# PyMBD algorithms runner
# Copyright Vera-Licona Research Group (C) 2015
# Author: Andrew Gainer-Dewar, Ph.D. <andrew.gainer.dewar@gmail.com>

# This file is part of MHSGenerationAlgorithms.

# MHSGenerationAlgorithms is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# MHSGenerationAlgorithms is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

from pymbd.diagnosis.problem import Problem
from pymbd.diagnosis.description import Description
import sys, os
import simplejson as json
import argparse

algname_map  = {
    'hsdag': 'hsdag',
    'hst': 'hst',
    'bool-iterative': 'bool-it-h5-stop',
    'bool-recursive': 'bool-rec-h1-oldr4',
    'staccato': 'staccato'
    }

# Set up argument processing
parser = argparse.ArgumentParser(description='MHS runner')

# Note: the help text will show input_file in the wrong place per AlgoRun, but it will still work
parser.add_argument("input_file", help="Input file to process")
parser.add_argument("-f", dest="output_file", default="out.dat", help="Output destination")

args = parser.parse_args()

# Fetch the relevant environment variables
try:
    cutoff_size = int(os.environ.get("CUTOFF_SIZE"))
except (ValueError, TypeError): # Invalid or no value
    cutoff_size = sys.maxint

if cutoff_size == 0:
    cutoff_size = sys.maxint

algarg = os.environ.get("ALGORITHM_NAME")
try:
    alg = algname_map[algarg]
except KeyError: # Invalid option
    raise ValueError("Invalid argument name {0} from environment variable ALGORITHM_NAME. Must use one of: {1}.".format(algarg, algname_map.keys()))

# Configure path and validation
script_dir = sys.path[0]

# Read the input file
with open(args.input_file) as input_file:
    input_json = json.load(input_file)

# Build the input to the PyMBD functions
sets = frozenset(frozenset(setlist) for setlist in input_json['sets'])
description = Description(sets)

# Run the chosen algorithm
problem = Problem()
MBDresult = problem.compute_with_description(description, alg, prune=True, cache=True, max_time=None, max_card=cutoff_size)

# Process the results
hs = MBDresult.get_diagnoses()
stats = MBDresult.get_stats()
formatted_hs = [list(h) for h in hs]
total_time = float(stats['total_time'])
results = input_json
results['transversals'] = formatted_hs
results['timeTaken'] = total_time
results['algName'] = algarg

# Write the results to the output file
with open(args.output_file, 'w') as output_file:
    # Pretty-print the output, but only if it isn't too big
    if len(formatted_hs) < 1024: # Check whether fewer than 1k MHSes
        indent_level = 4
    else:
        indent_level = None

    json.dump(results,
              output_file,
              indent = indent_level,
              separators = (',', ': '),
              iterable_as_array = True)

### Emacs configuration
# Local Variables:
# mode: python
# End:
