#!/usr/bin/env python

# MHS algorithm runner: FK
# Copyright Andrew Gainer-Dewar, Ph.D. (C) 2015 <andrew.gainer.dewar@gmail.com>

import json
import argparse
import tempfile
import timeit

# Set up argument processing
parser = argparse.ArgumentParser(description='MHS runner: FK')

# Note: the help text will show input_file in the wrong place per AlgoRun, but it will still work
parser.add_argument("input_file", action="store", help="Input file to process")
parser.add_argument("-t", action="store_true", dest="time_alg", default=False, help="Print run time of algorithm")
parser.add_argument('-f', nargs=1, action="store", dest="output_file", default="out.dat", help="Output destination")

args = parser.parse_args()

# Read the input file
with open(args.input_file) as input_file:
    input_json = json.load(input_file)

# Set up temporary files for input and output
with tempfile.NamedTemporaryFile() as temp_input_file:
    with tempfile.NamedTemporaryFile() as temp_output_file:
        # Generate the input file
        num_verts = max(vert for edge in input_json["sets"] for vert in edge)
        temp_input_file.write("{0} 1\n".format(num_verts))
        for edge in input_json["sets"]:
            # Print a 1 for each vertex in the edge and a 0 for each one not in the edge
            edge_as_charlist = ["0"] * num_verts
            for vert in edge:
                edge_as_charlist[vert-1] = "1"
            edge_as_string = " ".join(edge_as_charlist)
            temp_input_file.write(edge_as_string + "\n")

        temp_input_file.flush()

        # The provided executable crashes if the output destination is empty,
        # so we write out a starter line that satisfies it
        temp_output_file.write("{0} 1\n".format(num_verts))
        temp_output_file.flush()

        # Process the input file
        alg_call_string = "['./src/dual', '{0}', '{1}']".format(temp_input_file.name, temp_output_file.name)
        time_taken = timeit.timeit(stmt="subprocess.call({0}, stdout=devnull, stderr=devnull)".format(alg_call_string),
                                   setup="import subprocess, os; devnull=open(os.devnull, 'w')",
                                   number=1)

        if args.time_alg:
            print time_taken

        # Generate the results
        temp_output_file.seek(0)
        # Ignore the first line
        transversal_lines = temp_output_file.readlines()[1:]
        # Each line after that is a transversal, with a 1 in the position of each included
        # vertex and a 0 in each other position
        lineprocessor = lambda line: [i for (i, c) in enumerate(line.split(), start=1) if c=='1']
        transversals = [lineprocessor(line) for line in transversal_lines]
        results = input_json
        results["guaranteedMinimal"] = True
        results["guaranteedComplete"] = True
        results["transversals"] = transversals

# Write the results to the output file
with open(args.output_file, 'w') as output_file:
    json.dump(results, output_file)

### Emacs configuration
# Local Variables:
# mode: python
# End:
